[versions]
kotlin = "1.8.22"

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.8.20" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version = "3.1.0" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.0" }

[libraries]
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version = "7.4" }

[bundles]
